layout_spectrum: 0.7062184
typography_spectrum: 0.3835682
color:
  saturation: 0.8501497
  lightness: 0.4331338
  brandStrength: 0.3308794
  rhythmicContrast: 0.5536851
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
name: Shelleys collection
